title: ADA525
description: ADA525 course project
theme: Just the Docs Template

url: https://samiramousaviii.github.io/ADA525

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
