title: ADA525
description: ADA525 course project
theme: just-the-docs

url: https://samiramousaviii.github.io/ADA525

aux_links:
  Template Repository: https://github.com/samiramousaviii/ADA525


[Assignment 01 (CAD Mode1)](/_posts/2023-09-14-Assignment-01.md)

